<?php

namespace App\Config;

use CodeIgniter\Config\BaseConfig;

class Paytm extends BaseConfig
{
    /**
     * Paytm Environment
     * 'staging' for testing, 'production' for live
     */
    public $environment = 'staging';

    /**
     * Paytm Merchant Credentials
     * Replace with your actual credentials
     */
    public $merchantId = 'hhdaGX54213527799734'; // Your Paytm Merchant ID
    public $merchantKey = '1OLuORB&@k13LBXv'; // Your Paytm Merchant Key (Secret)
    public $website = 'WEBSTAGING'; // WEBSTAGING for test, DEFAULT for production
    public $industryType = 'Retail';
    public $channelId = 'WEB';

    /**
     * UPI Configuration
     * IMPORTANT: Use your Paytm Merchant UPI ID, not personal UPI
     * Format: merchantid@paytm (e.g., hhdaGX54213527799734@paytm)
     * This is automatically generated by Paytm for your merchant account
     */
    public $upiVpa = 'paytmqr1xxjq0ss3y@paytm'; // Paytm Merchant UPI ID
    public $payeeName = 'ABUZAR NULL MUNSHI'; // Your business/account name
    public $merchantCode = '4722'; // Merchant Category Code (MCC)
    
    /**
     * Paytm UPI Collect Configuration
     * For automatic payment verification via Paytm API
     */
    public $enableUpiCollect = true; // Enable UPI Collect API
    public $upiCollectTimeout = 300; // Timeout in seconds (5 minutes)

    /**
     * API URLs
     */
    public $apiUrls = [
        'staging' => [
            'transaction' => 'https://securegw-stage.paytm.in/theia/processTransaction',
            'status' => 'https://securegw-stage.paytm.in/order/status',
            'upi_collect' => 'https://securegw-stage.paytm.in/paymentservices/upi/collect',
            'upi_status' => 'https://securegw-stage.paytm.in/paymentservices/upi/status'
        ],
        'production' => [
            'transaction' => 'https://securegw.paytm.in/theia/processTransaction',
            'status' => 'https://securegw.paytm.in/order/status',
            'upi_collect' => 'https://securegw.paytm.in/paymentservices/upi/collect',
            'upi_status' => 'https://securegw.paytm.in/paymentservices/upi/status'
        ]
    ];

    /**
     * Get API URL based on environment
     */
    public function getApiUrl($type)
    {
        return $this->apiUrls[$this->environment][$type] ?? null;
    }

    /**
     * Check if in production mode
     */
    public function isProduction()
    {
        return $this->environment === 'production';
    }

    /**
     * Get callback URL
     */
    public function getCallbackUrl()
    {
        return base_url('api/paytm/callback');
    }

    /**
     * Get webhook URL
     */
    public function getWebhookUrl()
    {
        return base_url('api/paytm/webhook');
    }
}
